name: Build and Push to Private Registry

on:
  push:
    branches:
      - master  # Triggers the workflow when code is pushed to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - service_name: web-app
            dockerfile: ./EffereVexillum/Frontend/
            image_name: registry.neuhold-leonhard.work/vexillumfrontend:latest
          - service_name: backend-service
            dockerfile: ./EffereVexillum/BackendServer/
            image_name: registry.neuhold-leonhard.work/vexillumbackend:latest
            
    steps:
    # Step 1: Check out the code from the repository
    - name: Checkout Code
      uses: actions/checkout@v4
      
    # Step 2: Authenticate against your own custom Docker registry
    - name: Login to Custom Registry
      uses: docker/login-action@v3
      with:
        registry: https://registry.neuhold-leonhard.work
        username: ${{ secrets.DOCKER_REG_USERNAME }}
        password: ${{ secrets.DOCKER_REG_PASSWORD }}

    # Debug
    - name: Check Path
      run: pwd && ls -al && tree

    # Step 3: Build the image from the Dockerfile
    - name: Build Docker Image
      run: docker build -t ${{ matrix.image_name }} ${{ matrix.dockerfile }}

    # Step 4: Push the image to the registry
    - name: Push Docker Image
      run: docker push ${{ matrix.image_name }}

    # Step 5: Deployment on remote server
    - name: Execute Remote Commands via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 8022
        script: |
          echo "Successfully connected without a password!"
          kubectl rollout restart deployment
          echo "Completed rollout!"
